### ISSUE TITLE
No Highlight Image Generated

### ISSUE THREAD

**Issue by brichard1638** [rachelesrogers/highlightr#2]
Congratulations on creating a truly remarkable R package idea!

I have followed your vignette and conducted a preliminary analysis of this package. It appears that the very last line of R code does not generate the image you have presented.

I have replicated your code as described but no image is generated in RStudio. When the code **page_highlight** is entered into the console window, the following output is generated with no corresponding image:

`page_highlight`
`[1] "<div>  0 <div style=\"\n    height: 20px;\n    width: 200px;\n    display: inline-block;\n    background: linear-gradient(45deg, #F251FC , #F8FF1B );...`

Is there a step that is missing that was not documented or, alternatively is this a bug? If it is something on my end, please advise.

**Comment by rachelesrogers** [comment]
Thank you for reviewing my package! The final step was missing from the documentation, and has been updated in commit 00cf1755ca3087b9efd93fb3c4f04289f96b31fb
